CREATE TABLE `injury_histories` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `player_id` INT UNSIGNED NOT NULL,
  `injury_type` VARCHAR(255) NOT NULL,
  `recovery_games` INT NOT NULL,
  `performance_impact` DECIMAL(3,2) NOT NULL,
  `injury_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `recovery_date` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON DELETE CASCADE
);
