CREATE TABLE player_season_stats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    role VARCHAR(255),
    avg_points_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_rebounds_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_assists_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_steals_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_blocks_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_turnovers_per_game DECIMAL(5, 2) DEFAULT 0,
    avg_fouls_per_game DECIMAL(5, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);
